// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbXVOy3oKBf3IrTWLJcZtTP84DNtU5KKI',
    appId: '1:471701100406:web:c379ec81109fd1e8ea4c57',
    messagingSenderId: '471701100406',
    projectId: 'bijli-update-5d8bd',
    authDomain: 'bijli-update-5d8bd.firebaseapp.com',
    storageBucket: 'bijli-update-5d8bd.firebasestorage.app',
    measurementId: 'G-83D583XKKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9ZlQNKgT1EdJXfApYK3EJpDs4aBB3fqw',
    appId: '1:471701100406:android:6c5902658e84e754ea4c57',
    messagingSenderId: '471701100406',
    projectId: 'bijli-update-5d8bd',
    storageBucket: 'bijli-update-5d8bd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLfViZmXoe__ZF4CCXaxtEXLJeDfblI8U',
    appId: '1:471701100406:ios:fef6b69a30a33285ea4c57',
    messagingSenderId: '471701100406',
    projectId: 'bijli-update-5d8bd',
    storageBucket: 'bijli-update-5d8bd.firebasestorage.app',
    iosBundleId: 'com.example.bijliUpdate',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLfViZmXoe__ZF4CCXaxtEXLJeDfblI8U',
    appId: '1:471701100406:ios:fef6b69a30a33285ea4c57',
    messagingSenderId: '471701100406',
    projectId: 'bijli-update-5d8bd',
    storageBucket: 'bijli-update-5d8bd.firebasestorage.app',
    iosBundleId: 'com.example.bijliUpdate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbXVOy3oKBf3IrTWLJcZtTP84DNtU5KKI',
    appId: '1:471701100406:web:13c6cde634128dc6ea4c57',
    messagingSenderId: '471701100406',
    projectId: 'bijli-update-5d8bd',
    authDomain: 'bijli-update-5d8bd.firebaseapp.com',
    storageBucket: 'bijli-update-5d8bd.firebasestorage.app',
    measurementId: 'G-6Y3LCCJ343',
  );
}
